source "https://rubygems.org"

# Use github-pages for GitHub Pages compatibility
gem "github-pages", group: :jekyll_plugins
# Theme is specified via remote_theme in _config.yml
# gem "just-the-docs" is not needed here
gem "webrick", "~> 1.8"
